version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password

  app:
    image: user-profile-service:latest
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_DB:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "8080:8080"
      - "8443:8443"
    secrets:
      - postgres_user
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8888:80"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
