version: '3.8'

services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: user-service-test-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/test-data
    secrets:
      - postgres_user
      - postgres_password

  app:
    image: 'ghcr.io/iprody/iprody-devs-gr0000000011-user-profile/user-profile-service:latest'
    restart: always
    container_name: user-service-app-test
    environment:
      DATASOURCE_URL: 'jdbc:postgresql://db:5432/user'
      DATASOURCE_DRIVER: 'org.postgresql.Driver'
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
      - liquibase
    secrets:
      - postgres_user
      - postgres_password

  liquibase:
    image: liquibase/liquibase:latest
    container_name: user-service-liquibase-test
    depends_on:
      - db
    volumes:
      - ../liquibase/changelog:/liquibase/changelog
    command: >
      sh -c '
      liquibase
      --url=jdbc:postgresql://db:5432/user
      --changelog-file=./changelog/db.changelog-master.yaml
      --username=$$(cat /run/secrets/postgres_user)
      --password=$$(cat /run/secrets/postgres_password)
      update --contexts=test'
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_password:
    file: ../secrets/postgres_password.txt
  postgres_user:
    file: ../secrets/postgres_user.txt

volumes:
  postgres_db_data:
