version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: user
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password

  app:
    image: ghcr.io/iprody/iprody-devs-gr0000000011-user-profile/user-profile-service:latest
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "8080:8080"
      - "8443:8443"
    secrets:
      - postgres_user
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: default@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "8888:80"
    secrets:
      - pgadmin_password

secrets:
  postgres_password:
    file: ../secrets/postgres_password.txt
  postgres_user:
    file: ../secrets/postgres_user.txt
  pgadmin_password:
    file: ../secrets/pgadmin_password.txt
