services:
  db:
    image: 'postgres:latest'
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    image: 'ghcr.io/rustamabdusamatov4848/user-profile-service/user-profile-service:latest'
    restart: always
    container_name: user-service-app
    environment:
      DATASOURCE_URL: 'jdbc:postgresql://db:5432/postgres'
      DATASOURCE_DRIVER: 'org.postgresql.Driver'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db

  liquibase:
    image: liquibase/liquibase:latest
    container_name: user-service-liquibase
    depends_on:
      - db
    volumes:
      - ../liquibase/changelog:/liquibase/changelog
    command: >
      sh -c '
      liquibase
      --url=jdbc:postgresql://db:5432/postgres
      --changelog-file=./changelog/db.changelog-master.yaml
      --username=postgres
      --password=postgres
      update '

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=grafana
    depends_on:
      - app
    ports:
      - "8086:8086"
    healthcheck:
      test: [ "CMD","curl","-f","http://influxdb:8086/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - ../performance-testing:/scripts
    entrypoint: [ "sh", "-c", "k6 run --out influxdb=http://influxdb:8086/k6 /scripts/performance-tests.js" ]
