name: Build and Push Docker Image

on:
  push:
    branches: [ "develop" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clean with Maven
        run: mvn --batch-mode clean

      - name: Package with Maven
        run: mvn --batch-mode package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: set lower case repo name
        run: echo "REPO_NAME_LC=${REPO_NAME,,}" >> $GITHUB_ENV
        env:
          REPO_NAME: '${{ github.repository }}'

      - name: Build Docker image and push to GitHub Container Registry
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/user-profile-service:latest

