name: Run performance testing every day at 00:00

on:
  schedule:
    - cron: '0 0 * * * '

jobs:
  run_performance_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: ./user-profile-app/performance-testing-compose.yaml

